apiVersion: v1
kind: Service

metadata:
  name: cloud-project-service

spec:
  selector:
    app: cloud-project

  type: NodePort

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080