name: Cloud Infrastructure CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t cloud-infrastructure ./app

      - name: Verify Docker Image
        run: docker images

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate